---
label: product
hide_body: true
fields:
- name: product_name
  type: text
  config:
    required: true
  label: Product name
  description: name of product
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: Description
- name: product_picture
  type: file
  config:
    maxSize: 250
  label: product picture
pages:
- _posts/2019-07-12-test.md
